### ISSUE TITLE
add customers.create and subscription example

### ISSUE THREAD

**Issue by mariusa** [braintree/braintree_express_example#20]
Please add customers.create() and subscription example

Thanks!

**Comment by crookedneighbor** [comment]
@mariusa These example repos are intended as very basic integrations to get you started. 

The documentation around [creating customers](https://developers.braintreepayments.com/reference/request/customer/create/node) and [subscriptions](https://developers.braintreepayments.com/reference/request/subscription/create/node) should be sufficient. If you feel the examples there are not enough, feel free to leave feedback on the documentation website (link at the bottom of each page).
