### ISSUE TITLE
Demo.js

### ISSUE THREAD

**Issue by sidonaldson** [braintree/braintree_express_example#22]
### General information

* Environment: Sandbox
* Language, language version, and OS: Mac, Node etc.

### Issue description

I would like to query Demo.js and the need to include it in this example. I've had a look through the code and I believe it adds a few very small UI mods to the form - is it worth it? Could you update the docs to say what it does or remove it for brevity.

**Comment by crookedneighbor** [comment]
Thanks for bringing this up. I've been having similar thoughts about it. We'll discuss it as a team and let you know what we decide.

**Comment by sidonaldson** [comment]
@crookedneighbor Cool. Glad it's not seen as criticism. I'm currently integrating Braintree using the node sdk and the web drop-in, this project was super helpful, but it was hard to differentiate what the Drop-in UI supports 'out the box'. Thanks

**Comment by crookedneighbor** [comment]
Here's a PR to address it. https://github.com/braintree/braintree_express_example/pull/23

**Comment by sidonaldson** [comment]
Nice one. :)
