### ISSUE TITLE
Integrating Braintree

### ISSUE THREAD

**Issue by hadare1** [braintree/braintree_express_example#25]
Hi,

I’m trying to implement Braintree server with node.js I’m following the tutorial

And when I reach the nom test I have 3 test failures,   - 

  3 failing

  1) Checkouts show page respond with 200:
     Error: timeout of 2500ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Checkouts show page displays a failure page when transaction failed:
     Error: timeout of 2500ms exceeded. Ensure the done() callback is being called in this test.
  

  3) Checkouts create when the transaction is not successful when there are processor errors displays the transaction status:
     Error: timeout of 2500ms exceeded. Ensure the done() callback is being called in this test.

Beside that I’m trying to use my iOS app to send transaction to my server , I see in my log the payment nonce is. Sent to the server but I do not see the transactions in my Dashboard, 
My code is pretty much copied from the docs :

class ViewController: UIViewController {

  
    @IBOutlet weak var BUt: UIButton!
    var paymentMethod : BTPaymentMethodNonce?
    @IBAction func Butapped(_ sender: Any) {
        showDropIn(clientTokenOrTokenizationKey: "sandbox_t45fvztb_245nc5pjv2tyt3n8")
    }
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        BUt.isUserInteractionEnabled = false
        BUt.backgroundColor = UIColor.red
        fetchClientToken()
        // Do any additional setup after loading the view, typically from a nib.
    }

    func postNonceToServer(paymentMethodNonce: String) {
        // Update URL with your server
        let paymentURL = URL(string: "http://localhost:3000")!
        var request = URLRequest(url: paymentURL)
        request.httpBody = "payment_method_nonce=\(paymentMethodNonce)".data(using: String.Encoding.utf8)
        request.httpMethod = "POST"
        
        URLSession.shared.dataTask(with: request) { (data, response, error) -> Void in
            // TODO: Handle success or failure
            if let err = error {
                print("\(err.localizedDescription)")
            }
            else {print("success!")}
            }.resume()
    }
    
    @IBAction func PayTapped(_ sender: UIButton) {
        let paymentMethodNonce = "fake-valid-nonce"
        postNonceToServer(paymentMethodNonce: paymentMethodNonce)
    }
    
    func fetchClientToken() {
        // TODO: Switch this URL to your own authenticated API
        let clientTokenURL = NSURL(string: "http://localhost:3000")!
        let clientTokenRequest = NSMutableURLRequest(url: clientTokenURL as URL)
        clientTokenRequest.setValue("text/plain", forHTTPHeaderField: "Accept")
        
        URLSession.shared.dataTask(with: clientTokenRequest as URLRequest) { (data, response, error) -> Void in
            if let err = error {
                print("\(err.localizedDescription)")
            }
            // TODO: Handle errors
            let clientToken = String(data: data!, encoding: String.Encoding.utf8)
            
            // As an example, you may wish to present Drop-in at this point.
            // Continue to the next section to learn more...
            DispatchQueue.main.async {
                self.BUt.isUserInteractionEnabled = true
                self.BUt.backgroundColor = UIColor.white
            }

            }.resume()
    }
    
    
    func showDropIn(clientTokenOrTokenizationKey: String) {
        let request =  BTDropInRequest()
        let dropIn = BTDropInController(authorization: clientTokenOrTokenizationKey, request: request)
        { (controller, result, error) in
            if (error != nil) {
                print("ERROR")
            } else if (result?.isCancelled == true) {
                print("CANCELLED")
            } else if let result = result {
                // Use the BTDropInResult properties to update your UI
                // result.paymentOptionType
                // result.paymentMethod
                // result.paymentIcon
                // result.paymentDescription
            }
            controller.dismiss(animated: true, completion: nil)
        }
        self.present(dropIn!, animated: true, completion: nil)
    }
    

    
    func alert(message: String, title: String = "") {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let OKAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(OKAction)
        self.present(alertController, animated: true, completion: nil)
    }

}

Please let me know what am I doing wrong.

Thanks .

**Comment by crookedneighbor** [comment]
This repo is for a web implementation of the Braintree JavaScript SDK using an express server.

For help with your iOS integration please contact our support team https://articles.braintreepayments.com/forms/contact
