### ISSUE TITLE
Unable to checkout in sandbox

### ISSUE THREAD

**Issue by bhavinwebdesk** [braintree/braintree_express_example#28]
### General information

* Environment: =Sandbox
* Language, language version, and OS: Node v7.10.1 on Ubuntu 14.10

### Issue description

When I open "http://localhost:3000/checkouts/new" and try to click on "Test Transaction", I got following error in console.

`Uncaught TypeError: Cannot read property 'requestPaymentMethod' of undefined
    at HTMLFormElement.<anonymous> (new:14)`

I am not getting any error logs in console.

**Comment by crookedneighbor** [comment]
I'm not able to reproduce this.

![drop-in](https://user-images.githubusercontent.com/2916945/42461596-7edddea0-8366-11e8-94d9-e73d460d341b.gif)

Are you supplying your own API keys?

Have you made any changes to the code?

**Comment by bhavinwebdesk** [comment]
I have not made any changes. Here is my repo link:

[https://github.com/bhavinwebdesk/BrainTreeExampleWds](My Repo)

**Comment by crookedneighbor** [comment]
I was still unable to reproduce the issue with your fork.

Can you describe your steps to reproduce in more detail? Does the Drop-in UI load on your page at all?

Based on the error you describe, it sounds like the script is failing to load and setup the Drop-in.

**Comment by bhavinwebdesk** [comment]
Hi @crookedneighbor ,

Look like the issue is resolved after I connect my Braintree account with Paypal Sandbox account. Thanks for the help.

Closing now.
