### ISSUE TITLE
npm start error out and stopped

### ISSUE THREAD

**Issue by adamchenwei** [braintree/braintree_express_example#29]
### General information

* Environment: sandobx
* Language, language version, and OS: 

node v8.9.1

### Issue description

after npm install, it just error out when `npm start`

![screen shot 2018-08-01 at 6 18 04 am](https://user-images.githubusercontent.com/4201698/43516190-d3206f5c-9552-11e8-88b5-4ac9364ea26b.png)

**Comment by crookedneighbor** [comment]
You've missed step 2 of the setup instructions where it says to create a `.env` file with your API credentials.

**Comment by crookedneighbor** [comment]
https://github.com/braintree/braintree_express_example#setup-instructions
