### ISSUE TITLE
Error: 91564: Cannot use a payment_method_nonce more than once.

### ISSUE THREAD

**Issue by chasen-bettinger** [braintree/braintree_express_example#30]
### General information

* Environment: Sandbox
* Language, language version, and OS: Node v10.5.0, Windows Version 10.0.17134 Build 17134

### Issue description

1. npm i
2. get .env file setup
3. npm start
4. Try to create a transaction with your card only to realize you have to setup an account in the braintree dashboard
4. create account in braintree dashboard
5. make purchase and receive error

**Comment by crookedneighbor** [comment]
Can you explain a little more how to re-create the issue? Looks to me like you're submitting the payment method nonce twice so it's getting consumed.

**Comment by chasen-bettinger** [comment]
Can you be specific on how I should explain more? Start the server. Enter in payment information from a card you have. Receive an error message saying it's not an authorized card. Go into the Braintree dashboard and make an account. Use those credentials to make another purchase and then receive the error.

**Comment by crookedneighbor** [comment]
When you say:

> Receive an error message saying it's not an authorized card. Receive an error message saying it's not an authorized card

Do you mean that your Braintree account was not setup to process a specific card type? (Visa, Mastercard, Amex, etc)?

If so, did you re-enter it, or attempt to send the nonce you had previously created? If you just stop the app, and restart it, do you still see the error?

**Comment by chasen-bettinger** [comment]
More or less, yes. I didn't know that you were supposed to create a user in Braintree before entering in the card information. 

I attempted to send the nonce I had previously created, that was the problem. If I stop the app and restart it, I do not still see the error. 

My feedback is to include creating an account with a Braintree authorized card in the documentation. This error was confusing as a beginner; I wasn't sure what a nonce in the context of Braintree until reading now.

**Comment by crookedneighbor** [comment]
If you would like to submit a PR to clarify the instructions, feel free. I'm going to close this issue for now.

**Comment by crookedneighbor** [comment]
It shouldn't be necessary to create a customer to do any testing.

If you're having trouble, feel free to reach out to our support team: https://articles.braintreepayments.com/forms/contact

**Comment by fawadkhaliqkhan** [comment]
I was getting the same problem and finally figured it out. The culprit was my Volley network API which i was using to submit the POST request and to call TransactionRequest on server side. When there is delay in response it submitted the request again. I made the retry option to '0' and every fixed. How? check this [Link](https://stackoverflow.com/questions/27873001/android-volley-sending-data-twice)
